apiVersion: v1
kind: Namespace
metadata:
    name: reactroles
    labels:
        name: reactroles
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: reactroles-cfg
    namespace: reactroles
data:
    DISCORD_ROLECHANNEL: 'roleChannelIdHere'
    DISCORD_ROLEMESSAGE: 'roleMessageIdHere' # Will be logged out on first run when created,
    DISCORD_ROLEADDROLEID: 'roleIdHere' # Users with this role can add roles
    DISCORD_ROLEREMOVEROLEID: 'roleIdHere' # Users with this role can remove roles
    DISCORD_TOKEN: yourBotTokenHere
    POSTGRES_DB: reactroles
    POSTGRES_HOST: your.postgres.host
    POSTGRES_PASSWORD: 'yourDbPasswordHere'
    POSTGRES_PORT: 'yourPostgresPortHere'
    POSTGRES_SSL: disable # enable/disable Per your setup
    POSTGRES_TIMEZONE: Etc/UCT
    POSTGRES_USER: yourPostgresUserName
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: reactroles
    namespace: reactroles
spec:
    replicas: 1
    selector:
        matchLabels:
            app: reactroles
    template:
        metadata:
            labels:
                app: reactroles
        spec:
            containers:
                - name: reactroles
                  image: zaptross/reactroles:latest
                  resources:
                      limits:
                          memory: '128Mi'
                          cpu: '500m'
                  envFrom:
                      - configMapRef:
                            name: reactroles-cfg
