version: "3.9"
services:
  postgres:
    image: "postgres:latest"
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    restart: unless-stopped
  reactroles:
    image: zaptross/reactroles:test
    links:
      - "postgres:compose-postgres"
    depends_on:
      - postgres
    environment:
      - "DISCORD_TOKEN=${DISCORD_TOKEN}"
      - "DISCORD_ROLECHANNEL=${DISCORD_ROLECHANNEL}"
      - "DISCORD_ROLEMESSAGE=${DISCORD_ROLEMESSAGE}"
      - "DISCORD_ROLEADDROLEID=${DISCORD_ROLEADDROLEID}"
      - "DISCORD_ROLEREMOVEROLEID=${DISCORD_ROLEREMOVEROLEID}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "POSTGRES_HOST=compose-postgres"
      - "POSTGRES_SSL=${POSTGRES_SSL}"
      - "POSTGRES_TIMEZONE=${POSTGRES_TIMEZONE}"
