apiVersion: v1
kind: Secret
metadata:
  name: {{include "reactroles.fullname" .}}
data:
  {{- range $key, $val := .Values.reactroles.discord }}
  {{ $key }}: {{ $val | toString | b64enc }}
  {{- end }}
  {{- range $key, $val := .Values.reactroles.reactroles }}
  {{ $key }}: {{ $val | toString | b64enc }}
  {{- end }}
  {{- range $key, $val := .Values.reactroles.postgres }}
  {{ $key }}: {{ $val | toString | b64enc }}
  {{- end }}