apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "reactroles.fullname" .}}
data:
  {{- range $key, $val := .Values.reactroles.discord }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- range $key, $val := .Values.reactroles.postgres }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}