apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactroles
  labels: {{- include "reactroles.labels" . | nindent 4}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
    spec:
      containers:
        - name: {{.Chart.Name}}
          image: "{{ .Values.image.repository }}:{{.Values.image.tag | default .Chart.AppVersion }}"
          resources: {{- toYaml .Values.resources | nindent 12}}
          envFrom:
            - configMapRef:
                name: {{include "reactroles.fullname" .}}
